import fastify from 'fastify';
import cors from '@fastify/cors';
import staticPlugin from '@fastify/static';
import jwtPlugin from '@fastify/jwt';
import { Server } from 'socket.io';
import fs from 'fs';
import path from 'path';
import { env } from './env';
import { initDatabase } from './db';
import { healthRoutes } from './routes/health';
import { authRoutes } from './routes/auth';
import {
  ServerToClientEvents,
  ClientToServerEvents,
  InterServerEvents,
  SocketData,
} from './sockets/types';
import { registerSocketHandlers } from './sockets/handlers';

// ─── SSL Certificates (optional – generated by scripts/generate-certs.sh) ─────
const httpsOptions =
  fs.existsSync(env.CERT_PATH) && fs.existsSync(env.KEY_PATH)
    ? { key: fs.readFileSync(env.KEY_PATH), cert: fs.readFileSync(env.CERT_PATH) }
    : undefined;

// ─── Fastify instance ──────────────────────────────────────────────────────────
const appOptions: any = { logger: true };
if (httpsOptions) appOptions.https = httpsOptions;

const app = fastify(appOptions);

// ─── CORS ─────────────────────────────────────────────────────────────────────
app.register(cors, {
  origin: [env.FRONTEND_URL, 'http://localhost:5173', 'https://localhost:5173'],
  credentials: true,
});

// ─── JWT ──────────────────────────────────────────────────────────────────────
app.register(jwtPlugin, { secret: env.JWT_SECRET });

// ─── JWT authenticate decorator ───────────────────────────────────────────────
app.decorate('authenticate', async function (request: any, reply: any) {
  try {
    await request.jwtVerify();
  } catch (err) {
    reply.code(401).send({ error: 'Unauthorized' });
  }
});

// ─── Static files (test panel) ────────────────────────────────────────────────
app.register(staticPlugin, {
  root: path.join(__dirname, '../public'),
  prefix: '/test/',
});

// ─── REST Routes ──────────────────────────────────────────────────────────────
app.register(healthRoutes);
app.register(authRoutes);

// ─── Socket.io ────────────────────────────────────────────────────────────────
app.ready((err) => {
  if (err) throw err;

  const io = new Server<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>(
    app.server,
    {
      cors: {
        origin: [env.FRONTEND_URL, 'http://localhost:5173', 'https://localhost:5173'],
        methods: ['GET', 'POST'],
        credentials: true,
      },
      transports: ['websocket', 'polling'],
    }
  );

  registerSocketHandlers(io);
  app.log.info('Socket.io attached and ready');
});

// ─── Start ────────────────────────────────────────────────────────────────────
const start = async () => {
  try {
    await initDatabase();
    await app.listen({ port: env.PORT, host: '0.0.0.0' });
    console.log(`Server started over ${httpsOptions ? 'HTTPS' : 'HTTP'} on port ${env.PORT}`);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();
